--
-- PostgreSQL database dump
--

\restrict vlSJY3MTeQKRdU48fnEDdysSYjg3WlQDzB44I7RQC2daydHvZYbzd4q9TUivLVQ

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activity_logs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    action character varying(255) NOT NULL,
    details character varying(3000),
    entity_id bigint,
    entity_type character varying(255),
    ip_address character varying(255),
    success boolean NOT NULL,
    user_email character varying(255),
    user_id bigint NOT NULL,
    user_name character varying(255)
);


ALTER TABLE public.activity_logs OWNER TO postgres;

--
-- Name: activity_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.activity_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_chat_messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ai_chat_messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    content text NOT NULL,
    escalated boolean,
    role text NOT NULL,
    satisfied boolean,
    chat_id bigint NOT NULL
);


ALTER TABLE public.ai_chat_messages OWNER TO postgres;

--
-- Name: ai_chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ai_chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_chats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ai_chats (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    message_count integer,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    candidate_id bigint NOT NULL
);


ALTER TABLE public.ai_chats OWNER TO postgres;

--
-- Name: ai_chats_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ai_chats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_chats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attendance (
    id bigint NOT NULL,
    attendance_date date,
    event_type character varying(255),
    present boolean NOT NULL,
    candidate_id bigint
);


ALTER TABLE public.attendance OWNER TO postgres;

--
-- Name: attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_logs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    action character varying(255),
    details character varying(255),
    device_info character varying(255),
    ip_address character varying(255),
    role character varying(255),
    success boolean,
    user_email character varying(255),
    user_id bigint,
    user_name character varying(255)
);


ALTER TABLE public.auth_logs OWNER TO postgres;

--
-- Name: auth_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: baptism_events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.baptism_events (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    description character varying(255),
    event_date date NOT NULL,
    event_name character varying(255) NOT NULL,
    location character varying(255) NOT NULL,
    officiating_pastor character varying(255) NOT NULL,
    status character varying(255),
    CONSTRAINT baptism_events_status_check CHECK (((status)::text = ANY ((ARRAY['PLANNED'::character varying, 'CONFIRMED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.baptism_events OWNER TO postgres;

--
-- Name: baptism_events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.baptism_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.baptism_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: baptism_interview; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.baptism_interview (
    id bigint NOT NULL,
    approved boolean NOT NULL,
    feedback character varying(3000),
    interview_date date,
    candidate_id bigint,
    interviewer_id bigint
);


ALTER TABLE public.baptism_interview OWNER TO postgres;

--
-- Name: baptism_interview_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.baptism_interview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.baptism_interview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: baptism_photo_urls; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.baptism_photo_urls (
    baptism_id bigint NOT NULL,
    photo_urls character varying(255)
);


ALTER TABLE public.baptism_photo_urls OWNER TO postgres;

--
-- Name: baptism_request_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.baptism_request_logs (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    candidate_id bigint,
    details character varying(255),
    event_id bigint,
    performed_by character varying(255),
    request_id bigint,
    "timestamp" timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.baptism_request_logs OWNER TO postgres;

--
-- Name: baptism_request_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.baptism_request_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.baptism_request_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: baptisms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.baptisms (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    approved boolean NOT NULL,
    baptism_date date NOT NULL,
    baptism_order integer NOT NULL,
    baptized boolean NOT NULL,
    certificate_number character varying(255),
    certificate_signed boolean NOT NULL,
    confirmed_at timestamp(6) without time zone,
    location character varying(255),
    officiating_pastor character varying(255),
    request_status character varying(255),
    requested_at timestamp(6) without time zone,
    signed_at timestamp(6) without time zone,
    sponsor_name character varying(255),
    witness_name character varying(255),
    candidate_id bigint,
    event_id bigint,
    CONSTRAINT baptisms_request_status_check CHECK (((request_status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'BAPTIZED'::character varying, 'CERTIFICATE_GENERATED'::character varying, 'CERTIFICATE_SIGNED'::character varying, 'TRANSFERRED_TO_CMS'::character varying])::text[])))
);


ALTER TABLE public.baptisms OWNER TO postgres;

--
-- Name: baptisms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.baptisms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.baptisms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bible_studies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bible_studies (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    chapter character varying(255),
    content text,
    description text,
    duration integer,
    schedule timestamp(6) without time zone,
    status character varying(255),
    title character varying(255) NOT NULL,
    verse character varying(255),
    instructor_id bigint,
    CONSTRAINT bible_studies_status_check CHECK (((status)::text = ANY ((ARRAY['SCHEDULED'::character varying, 'ONGOING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.bible_studies OWNER TO postgres;

--
-- Name: bible_studies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bible_studies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bible_studies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bible_study_participants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bible_study_participants (
    bible_study_id bigint NOT NULL,
    candidate_id bigint NOT NULL
);


ALTER TABLE public.bible_study_participants OWNER TO postgres;

--
-- Name: candidates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.candidates (
    id bigint NOT NULL,
    address character varying(255),
    baptism_date date,
    created_at timestamp(6) without time zone,
    date_of_birth date,
    email character varying(255),
    full_name character varying(255),
    gender character varying(255),
    instructor_approved boolean NOT NULL,
    phone character varying(255),
    preferred_course_language character varying(255),
    profile_picture_path character varying(255),
    referral_source character varying(255),
    status character varying(255),
    church_id bigint,
    instructor_id bigint,
    CONSTRAINT candidates_status_check CHECK (((status)::text = ANY ((ARRAY['REGISTERED'::character varying, 'IN_PROGRESS'::character varying, 'READY_FOR_BAPTISM'::character varying, 'BAPTISM_REQUEST_PENDING'::character varying, 'APPROVED_FOR_BAPTISM'::character varying, 'BAPTIZED'::character varying, 'CERTIFICATE_GENERATED'::character varying, 'CERTIFICATE_SIGNED'::character varying, 'COURSE_COMPLETED'::character varying, 'TRANSFERRED_TO_CMS'::character varying])::text[])))
);


ALTER TABLE public.candidates OWNER TO postgres;

--
-- Name: candidates_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.candidates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.candidates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: certificate_download_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.certificate_download_logs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    baptism_id bigint,
    candidate_id bigint,
    candidate_name character varying(255),
    certificate_number character varying(255),
    device_info character varying(255),
    downloaded_by character varying(255),
    downloaded_by_name character varying(255),
    ip_address character varying(255),
    role character varying(255)
);


ALTER TABLE public.certificate_download_logs OWNER TO postgres;

--
-- Name: certificate_download_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.certificate_download_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.certificate_download_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: church_fields; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.church_fields (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    active boolean NOT NULL,
    address character varying(255),
    code character varying(255),
    email character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255),
    union_id bigint NOT NULL
);


ALTER TABLE public.church_fields OWNER TO postgres;

--
-- Name: church_fields_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.church_fields ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.church_fields_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: churches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.churches (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    active boolean NOT NULL,
    address character varying(255),
    church_name character varying(255) NOT NULL,
    email character varying(255),
    phone character varying(255),
    district_id bigint,
    pastor_id bigint
);


ALTER TABLE public.churches OWNER TO postgres;

--
-- Name: churches_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.churches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.churches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cohort_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cohort_members (
    id bigint NOT NULL,
    approved_at timestamp(6) without time zone,
    enrolled_at timestamp(6) without time zone,
    status character varying(255),
    candidate_id bigint NOT NULL,
    cohort_id bigint NOT NULL,
    CONSTRAINT cohort_members_status_check CHECK (((status)::text = ANY ((ARRAY['ENROLLED'::character varying, 'APPROVED'::character varying, 'COMPLETED'::character varying, 'WITHDRAWN'::character varying])::text[])))
);


ALTER TABLE public.cohort_members OWNER TO postgres;

--
-- Name: cohort_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cohort_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cohort_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cohorts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cohorts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    capacity integer,
    cohort_code character varying(255),
    cohort_name character varying(255),
    end_date date,
    start_date date,
    status character varying(255),
    church_id bigint,
    instructor_id bigint,
    CONSTRAINT cohorts_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'ACTIVE'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.cohorts OWNER TO postgres;

--
-- Name: cohorts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cohorts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cohorts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    active boolean NOT NULL,
    description character varying(2000),
    name character varying(255) NOT NULL,
    church_id bigint,
    head_member_id bigint
);


ALTER TABLE public.departments OWNER TO postgres;

--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: district_assignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.district_assignments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    end_date date,
    performed_by character varying(255),
    reason character varying(255),
    start_date date NOT NULL,
    status character varying(255) NOT NULL,
    district_id bigint NOT NULL,
    pastor_id bigint NOT NULL,
    CONSTRAINT district_assignments_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'TRANSFERRED'::character varying, 'ENDED'::character varying])::text[])))
);


ALTER TABLE public.district_assignments OWNER TO postgres;

--
-- Name: district_assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.district_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.district_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: districts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.districts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    active boolean NOT NULL,
    address character varying(255),
    code character varying(255),
    email character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255),
    field_id bigint NOT NULL
);


ALTER TABLE public.districts OWNER TO postgres;

--
-- Name: districts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.districts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.districts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_verification_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.email_verification_tokens (
    id bigint NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    used boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.email_verification_tokens OWNER TO postgres;

--
-- Name: email_verification_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.email_verification_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_verification_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: field_assignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.field_assignments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    end_date date,
    performed_by character varying(255),
    reason character varying(255),
    start_date date NOT NULL,
    status character varying(255) NOT NULL,
    field_id bigint NOT NULL,
    head_id bigint NOT NULL,
    CONSTRAINT field_assignments_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ENDED'::character varying])::text[])))
);


ALTER TABLE public.field_assignments OWNER TO postgres;

--
-- Name: field_assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.field_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.field_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: first_church_elders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.first_church_elders (
    id bigint NOT NULL,
    active boolean NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    phone character varying(255),
    church_id bigint NOT NULL
);


ALTER TABLE public.first_church_elders OWNER TO postgres;

--
-- Name: first_church_elders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.first_church_elders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.first_church_elders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: human_support_messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.human_support_messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    ai_chat_id bigint,
    message text NOT NULL,
    read_by_candidate boolean,
    read_by_recipient boolean,
    recipient_role character varying(255) NOT NULL,
    is_reply boolean,
    status character varying(30) NOT NULL,
    subject character varying(255) NOT NULL,
    candidate_id bigint NOT NULL,
    parent_id bigint,
    recipient_id bigint NOT NULL,
    sender_id bigint
);


ALTER TABLE public.human_support_messages OWNER TO postgres;

--
-- Name: human_support_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.human_support_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.human_support_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instructors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.instructors (
    id bigint NOT NULL,
    active boolean NOT NULL,
    email character varying(255),
    full_name character varying(255),
    phone character varying(255),
    qualification character varying(255),
    years_of_service integer NOT NULL,
    church_id bigint NOT NULL
);


ALTER TABLE public.instructors OWNER TO postgres;

--
-- Name: instructors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.instructors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.instructors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leadership_audit_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.leadership_audit_logs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    district_id bigint,
    district_name character varying(255),
    event_date timestamp(6) without time zone,
    event_type character varying(255) NOT NULL,
    field_id bigint,
    field_name character varying(255),
    leader_id bigint,
    leader_name character varying(255),
    new_assignment_id bigint,
    new_assignment_summary character varying(255),
    performed_by character varying(255),
    previous_assignment_id bigint,
    previous_assignment_summary character varying(255),
    reason character varying(255),
    CONSTRAINT leadership_audit_logs_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['HEAD_OF_DISTRICT_TRANSFERRED'::character varying, 'HEAD_OF_DISTRICT_REASSIGNED'::character varying, 'HEAD_OF_FIELD_REPLACED'::character varying, 'HEAD_OF_FIELD_APPOINTED'::character varying])::text[])))
);


ALTER TABLE public.leadership_audit_logs OWNER TO postgres;

--
-- Name: leadership_audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.leadership_audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leadership_audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lesson_answer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lesson_answer (
    id bigint NOT NULL,
    correct boolean NOT NULL,
    selected_answer character varying(255),
    candidate_id bigint,
    question_id bigint
);


ALTER TABLE public.lesson_answer OWNER TO postgres;

--
-- Name: lesson_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lesson_answer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lesson_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lesson_attempts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lesson_attempts (
    id bigint NOT NULL,
    attempt_number integer NOT NULL,
    completed_at timestamp(6) without time zone,
    passed boolean NOT NULL,
    score integer NOT NULL,
    started_at timestamp(6) without time zone,
    candidate_id bigint,
    lesson_id bigint
);


ALTER TABLE public.lesson_attempts OWNER TO postgres;

--
-- Name: lesson_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lesson_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lesson_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lesson_documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lesson_documents (
    id bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    file_size bigint NOT NULL,
    file_type character varying(255),
    file_url character varying(255) NOT NULL,
    lesson_id bigint NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.lesson_documents OWNER TO postgres;

--
-- Name: lesson_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lesson_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lesson_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lesson_question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lesson_question (
    id bigint NOT NULL,
    correct_answer character varying(255),
    order_index integer NOT NULL,
    question character varying(255),
    lesson_id bigint
);


ALTER TABLE public.lesson_question OWNER TO postgres;

--
-- Name: lesson_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lesson_question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lesson_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lesson_question_options; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lesson_question_options (
    lesson_question_id bigint NOT NULL,
    options character varying(255)
);


ALTER TABLE public.lesson_question_options OWNER TO postgres;

--
-- Name: lessons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lessons (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    category character varying(255),
    completed boolean NOT NULL,
    completed_at timestamp(6) without time zone,
    completion_percentage integer NOT NULL,
    description text,
    description_rw text,
    document_url character varying(255),
    duration_minutes integer,
    lesson_date date,
    lesson_order integer NOT NULL,
    lesson_title character varying(255),
    max_attempts integer NOT NULL,
    notes text,
    notes_rw text,
    obtained_score integer NOT NULL,
    required_score integer NOT NULL,
    started_at timestamp(6) without time zone,
    status character varying(255),
    title_rw character varying(255),
    bible_study_id bigint,
    candidate_id bigint,
    instructor_id bigint,
    CONSTRAINT lessons_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_STARTED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.lessons OWNER TO postgres;

--
-- Name: lessons_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lessons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lessons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member_departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.member_departments (
    member_id bigint NOT NULL,
    department_id bigint NOT NULL
);


ALTER TABLE public.member_departments OWNER TO postgres;

--
-- Name: members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.members (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    baptism_date date,
    leadership_role character varying(255),
    local_church character varying(255),
    pastoral_notes character varying(255),
    status character varying(255),
    transfer_history character varying(255),
    candidate_id bigint,
    CONSTRAINT members_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'TRANSFERRED'::character varying, 'DECEASED'::character varying])::text[])))
);


ALTER TABLE public.members OWNER TO postgres;

--
-- Name: members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: membership_transfer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.membership_transfer (
    id bigint NOT NULL,
    initiator_type character varying(255),
    reason character varying(255),
    status character varying(255),
    approved_by_from_church_id bigint,
    approved_by_to_church_id bigint,
    from_church_id bigint,
    member_id bigint,
    requested_by_id bigint,
    to_church_id bigint,
    CONSTRAINT membership_transfer_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED_FROM_CHURCH'::character varying, 'APPROVED_TO_CHURCH'::character varying, 'COMPLETED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.membership_transfer OWNER TO postgres;

--
-- Name: membership_transfer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.membership_transfer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.membership_transfer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message_logs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    action character varying(255),
    conversation_id character varying(255),
    message_preview character varying(255),
    receiver_id bigint,
    receiver_name character varying(255),
    sender_id bigint,
    sender_name character varying(255),
    subject character varying(255)
);


ALTER TABLE public.message_logs OWNER TO postgres;

--
-- Name: message_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.message_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    content text NOT NULL,
    read boolean NOT NULL,
    subject character varying(50),
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


ALTER TABLE public.messages OWNER TO postgres;

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    is_read boolean NOT NULL,
    message character varying(3000),
    title character varying(255),
    type character varying(255),
    user_id bigint,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['INSTRUCTOR_ASSIGNED'::character varying, 'NEW_LESSON'::character varying, 'BAPTISM_EVENT_AVAILABLE'::character varying, 'BAPTISM_REGISTERED'::character varying, 'BAPTISM_CERTIFICATE_READY'::character varying, 'CHURCH_ANNOUNCEMENT'::character varying, 'LESSON_REMINDER'::character varying, 'BAPTISM_APPROVAL'::character varying, 'BAPTISM_SCHEDULE'::character varying, 'SYSTEM'::character varying, 'PROGRESS_UPDATE'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    used boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.password_reset_tokens OWNER TO postgres;

--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_audit_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.report_audit_logs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    filters_used text,
    format character varying(255),
    generated_by character varying(255) NOT NULL,
    generated_by_name character varying(255),
    generated_by_role character varying(255),
    generation_date timestamp(6) without time zone,
    record_count integer,
    report_name character varying(255) NOT NULL
);


ALTER TABLE public.report_audit_logs OWNER TO postgres;

--
-- Name: report_audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.report_audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spiritual_preparations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.spiritual_preparations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    bible_reading_score integer NOT NULL,
    character_assessment integer NOT NULL,
    mentor_notes character varying(255),
    prayer_meetings integer NOT NULL,
    prayer_request character varying(255),
    readiness_score double precision NOT NULL,
    ready_for_baptism boolean NOT NULL,
    testimony character varying(255),
    worship_attendance integer NOT NULL,
    candidate_id bigint
);


ALTER TABLE public.spiritual_preparations OWNER TO postgres;

--
-- Name: spiritual_preparations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.spiritual_preparations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spiritual_preparations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spiritual_progress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.spiritual_progress (
    id bigint NOT NULL,
    church_participation_score integer NOT NULL,
    mentor_notes character varying(3000),
    prayer_score integer NOT NULL,
    readiness_status character varying(255),
    scripture_reading_score integer NOT NULL,
    candidate_id bigint,
    CONSTRAINT spiritual_progress_readiness_status_check CHECK (((readiness_status)::text = ANY ((ARRAY['NOT_READY'::character varying, 'IN_PROGRESS'::character varying, 'READY_FOR_BAPTISM'::character varying])::text[])))
);


ALTER TABLE public.spiritual_progress OWNER TO postgres;

--
-- Name: spiritual_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.spiritual_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spiritual_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.unions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    active boolean NOT NULL,
    address character varying(255),
    code character varying(255),
    email character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255)
);


ALTER TABLE public.unions OWNER TO postgres;

--
-- Name: unions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.unions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_by character varying(255),
    address character varying(255),
    avatar text,
    date_of_birth date,
    email character varying(255) NOT NULL,
    email_verified boolean NOT NULL,
    emergency_contact character varying(255),
    enabled boolean NOT NULL,
    full_name character varying(255) NOT NULL,
    gender character varying(255),
    password character varying(255) NOT NULL,
    phone character varying(255),
    preferred_language character varying(255),
    role character varying(255),
    signature_path character varying(255),
    two_factor_code character varying(255),
    two_factor_code_expiry timestamp(6) without time zone,
    two_factor_enabled boolean NOT NULL,
    church_id bigint,
    district_id bigint,
    field_id bigint,
    union_id bigint
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: activity_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.activity_logs (id, created_at, updated_at, action, details, entity_id, entity_type, ip_address, success, user_email, user_id, user_name) FROM stdin;
\.


--
-- Data for Name: ai_chat_messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ai_chat_messages (id, created_at, updated_at, created_by, updated_by, content, escalated, role, satisfied, chat_id) FROM stdin;
\.


--
-- Data for Name: ai_chats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ai_chats (id, created_at, updated_at, created_by, updated_by, message_count, status, title, candidate_id) FROM stdin;
\.


--
-- Data for Name: attendance; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attendance (id, attendance_date, event_type, present, candidate_id) FROM stdin;
\.


--
-- Data for Name: auth_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_logs (id, created_at, updated_at, action, details, device_info, ip_address, role, success, user_email, user_id, user_name) FROM stdin;
\.


--
-- Data for Name: baptism_events; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.baptism_events (id, created_at, updated_at, created_by, updated_by, description, event_date, event_name, location, officiating_pastor, status) FROM stdin;
\.


--
-- Data for Name: baptism_interview; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.baptism_interview (id, approved, feedback, interview_date, candidate_id, interviewer_id) FROM stdin;
\.


--
-- Data for Name: baptism_photo_urls; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.baptism_photo_urls (baptism_id, photo_urls) FROM stdin;
\.


--
-- Data for Name: baptism_request_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.baptism_request_logs (id, action, candidate_id, details, event_id, performed_by, request_id, "timestamp") FROM stdin;
\.


--
-- Data for Name: baptisms; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.baptisms (id, created_at, updated_at, created_by, updated_by, approved, baptism_date, baptism_order, baptized, certificate_number, certificate_signed, confirmed_at, location, officiating_pastor, request_status, requested_at, signed_at, sponsor_name, witness_name, candidate_id, event_id) FROM stdin;
\.


--
-- Data for Name: bible_studies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bible_studies (id, created_at, updated_at, created_by, updated_by, chapter, content, description, duration, schedule, status, title, verse, instructor_id) FROM stdin;
\.


--
-- Data for Name: bible_study_participants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bible_study_participants (bible_study_id, candidate_id) FROM stdin;
\.


--
-- Data for Name: candidates; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.candidates (id, address, baptism_date, created_at, date_of_birth, email, full_name, gender, instructor_approved, phone, preferred_course_language, profile_picture_path, referral_source, status, church_id, instructor_id) FROM stdin;
\.


--
-- Data for Name: certificate_download_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.certificate_download_logs (id, created_at, updated_at, baptism_id, candidate_id, candidate_name, certificate_number, device_info, downloaded_by, downloaded_by_name, ip_address, role) FROM stdin;
\.


--
-- Data for Name: church_fields; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.church_fields (id, created_at, updated_at, created_by, updated_by, active, address, code, email, name, phone, union_id) FROM stdin;
\.


--
-- Data for Name: churches; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.churches (id, created_at, updated_at, created_by, updated_by, active, address, church_name, email, phone, district_id, pastor_id) FROM stdin;
\.


--
-- Data for Name: cohort_members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cohort_members (id, approved_at, enrolled_at, status, candidate_id, cohort_id) FROM stdin;
\.


--
-- Data for Name: cohorts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cohorts (id, created_at, updated_at, created_by, updated_by, capacity, cohort_code, cohort_name, end_date, start_date, status, church_id, instructor_id) FROM stdin;
\.


--
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departments (id, created_at, updated_at, created_by, updated_by, active, description, name, church_id, head_member_id) FROM stdin;
\.


--
-- Data for Name: district_assignments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.district_assignments (id, created_at, updated_at, end_date, performed_by, reason, start_date, status, district_id, pastor_id) FROM stdin;
\.


--
-- Data for Name: districts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.districts (id, created_at, updated_at, created_by, updated_by, active, address, code, email, name, phone, field_id) FROM stdin;
\.


--
-- Data for Name: email_verification_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.email_verification_tokens (id, expiry_date, token, used, user_id) FROM stdin;
\.


--
-- Data for Name: field_assignments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.field_assignments (id, created_at, updated_at, end_date, performed_by, reason, start_date, status, field_id, head_id) FROM stdin;
\.


--
-- Data for Name: first_church_elders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.first_church_elders (id, active, email, full_name, phone, church_id) FROM stdin;
\.


--
-- Data for Name: human_support_messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.human_support_messages (id, created_at, updated_at, created_by, updated_by, ai_chat_id, message, read_by_candidate, read_by_recipient, recipient_role, is_reply, status, subject, candidate_id, parent_id, recipient_id, sender_id) FROM stdin;
\.


--
-- Data for Name: instructors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.instructors (id, active, email, full_name, phone, qualification, years_of_service, church_id) FROM stdin;
\.


--
-- Data for Name: leadership_audit_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.leadership_audit_logs (id, created_at, updated_at, district_id, district_name, event_date, event_type, field_id, field_name, leader_id, leader_name, new_assignment_id, new_assignment_summary, performed_by, previous_assignment_id, previous_assignment_summary, reason) FROM stdin;
\.


--
-- Data for Name: lesson_answer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lesson_answer (id, correct, selected_answer, candidate_id, question_id) FROM stdin;
\.


--
-- Data for Name: lesson_attempts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lesson_attempts (id, attempt_number, completed_at, passed, score, started_at, candidate_id, lesson_id) FROM stdin;
\.


--
-- Data for Name: lesson_documents; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lesson_documents (id, file_name, file_size, file_type, file_url, lesson_id, uploaded_at) FROM stdin;
\.


--
-- Data for Name: lesson_question; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lesson_question (id, correct_answer, order_index, question, lesson_id) FROM stdin;
\.


--
-- Data for Name: lesson_question_options; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lesson_question_options (lesson_question_id, options) FROM stdin;
\.


--
-- Data for Name: lessons; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lessons (id, created_at, updated_at, created_by, updated_by, category, completed, completed_at, completion_percentage, description, description_rw, document_url, duration_minutes, lesson_date, lesson_order, lesson_title, max_attempts, notes, notes_rw, obtained_score, required_score, started_at, status, title_rw, bible_study_id, candidate_id, instructor_id) FROM stdin;
\.


--
-- Data for Name: member_departments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.member_departments (member_id, department_id) FROM stdin;
\.


--
-- Data for Name: members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.members (id, created_at, updated_at, created_by, updated_by, baptism_date, leadership_role, local_church, pastoral_notes, status, transfer_history, candidate_id) FROM stdin;
\.


--
-- Data for Name: membership_transfer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.membership_transfer (id, initiator_type, reason, status, approved_by_from_church_id, approved_by_to_church_id, from_church_id, member_id, requested_by_id, to_church_id) FROM stdin;
\.


--
-- Data for Name: message_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.message_logs (id, created_at, updated_at, action, conversation_id, message_preview, receiver_id, receiver_name, sender_id, sender_name, subject) FROM stdin;
\.


--
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messages (id, created_at, updated_at, created_by, updated_by, content, read, subject, receiver_id, sender_id) FROM stdin;
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, created_at, updated_at, created_by, updated_by, is_read, message, title, type, user_id) FROM stdin;
\.


--
-- Data for Name: password_reset_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_reset_tokens (id, expiry_date, token, used, user_id) FROM stdin;
\.


--
-- Data for Name: report_audit_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.report_audit_logs (id, created_at, updated_at, filters_used, format, generated_by, generated_by_name, generated_by_role, generation_date, record_count, report_name) FROM stdin;
\.


--
-- Data for Name: spiritual_preparations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.spiritual_preparations (id, created_at, updated_at, created_by, updated_by, bible_reading_score, character_assessment, mentor_notes, prayer_meetings, prayer_request, readiness_score, ready_for_baptism, testimony, worship_attendance, candidate_id) FROM stdin;
\.


--
-- Data for Name: spiritual_progress; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.spiritual_progress (id, church_participation_score, mentor_notes, prayer_score, readiness_status, scripture_reading_score, candidate_id) FROM stdin;
\.


--
-- Data for Name: unions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.unions (id, created_at, updated_at, created_by, updated_by, active, address, code, email, name, phone) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, created_at, updated_at, created_by, updated_by, address, avatar, date_of_birth, email, email_verified, emergency_contact, enabled, full_name, gender, password, phone, preferred_language, role, signature_path, two_factor_code, two_factor_code_expiry, two_factor_enabled, church_id, district_id, field_id, union_id) FROM stdin;
1	2026-07-21 12:46:52.815074	2026-07-21 12:46:52.815092	\N	\N	\N	\N	\N	admin@church.org	f	\N	t	System Administrator	\N	$2a$10$OpPQSYZCB2Ez9qfOUeTrsOcuWnCXxEwdEqGz3yfdR/2kX4VwG8u0.	0000000000	en	ADMIN	\N	\N	\N	f	\N	\N	\N	\N
\.


--
-- Name: activity_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.activity_logs_id_seq', 1, false);


--
-- Name: ai_chat_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ai_chat_messages_id_seq', 1, false);


--
-- Name: ai_chats_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ai_chats_id_seq', 1, false);


--
-- Name: attendance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.attendance_id_seq', 1, false);


--
-- Name: auth_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_logs_id_seq', 1, false);


--
-- Name: baptism_events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.baptism_events_id_seq', 1, false);


--
-- Name: baptism_interview_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.baptism_interview_id_seq', 1, false);


--
-- Name: baptism_request_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.baptism_request_logs_id_seq', 1, false);


--
-- Name: baptisms_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.baptisms_id_seq', 1, false);


--
-- Name: bible_studies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bible_studies_id_seq', 1, false);


--
-- Name: candidates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.candidates_id_seq', 1, false);


--
-- Name: certificate_download_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.certificate_download_logs_id_seq', 1, false);


--
-- Name: church_fields_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.church_fields_id_seq', 1, false);


--
-- Name: churches_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.churches_id_seq', 1, false);


--
-- Name: cohort_members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cohort_members_id_seq', 1, false);


--
-- Name: cohorts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cohorts_id_seq', 1, false);


--
-- Name: departments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departments_id_seq', 1, false);


--
-- Name: district_assignments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.district_assignments_id_seq', 1, false);


--
-- Name: districts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.districts_id_seq', 1, false);


--
-- Name: email_verification_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.email_verification_tokens_id_seq', 1, false);


--
-- Name: field_assignments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.field_assignments_id_seq', 1, false);


--
-- Name: first_church_elders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.first_church_elders_id_seq', 1, false);


--
-- Name: human_support_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.human_support_messages_id_seq', 1, false);


--
-- Name: instructors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.instructors_id_seq', 1, false);


--
-- Name: leadership_audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.leadership_audit_logs_id_seq', 1, false);


--
-- Name: lesson_answer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lesson_answer_id_seq', 1, false);


--
-- Name: lesson_attempts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lesson_attempts_id_seq', 1, false);


--
-- Name: lesson_documents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lesson_documents_id_seq', 1, false);


--
-- Name: lesson_question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lesson_question_id_seq', 1, false);


--
-- Name: lessons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lessons_id_seq', 1, false);


--
-- Name: members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.members_id_seq', 1, false);


--
-- Name: membership_transfer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.membership_transfer_id_seq', 1, false);


--
-- Name: message_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.message_logs_id_seq', 1, false);


--
-- Name: messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messages_id_seq', 1, false);


--
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_id_seq', 1, false);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.password_reset_tokens_id_seq', 1, false);


--
-- Name: report_audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.report_audit_logs_id_seq', 1, false);


--
-- Name: spiritual_preparations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.spiritual_preparations_id_seq', 1, false);


--
-- Name: spiritual_progress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.spiritual_progress_id_seq', 1, false);


--
-- Name: unions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.unions_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: activity_logs activity_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activity_logs
    ADD CONSTRAINT activity_logs_pkey PRIMARY KEY (id);


--
-- Name: ai_chat_messages ai_chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_chat_messages
    ADD CONSTRAINT ai_chat_messages_pkey PRIMARY KEY (id);


--
-- Name: ai_chats ai_chats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_chats
    ADD CONSTRAINT ai_chats_pkey PRIMARY KEY (id);


--
-- Name: attendance attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);


--
-- Name: auth_logs auth_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_logs
    ADD CONSTRAINT auth_logs_pkey PRIMARY KEY (id);


--
-- Name: baptism_events baptism_events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baptism_events
    ADD CONSTRAINT baptism_events_pkey PRIMARY KEY (id);


--
-- Name: baptism_interview baptism_interview_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baptism_interview
    ADD CONSTRAINT baptism_interview_pkey PRIMARY KEY (id);


--
-- Name: baptism_request_logs baptism_request_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baptism_request_logs
    ADD CONSTRAINT baptism_request_logs_pkey PRIMARY KEY (id);


--
-- Name: baptisms baptisms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baptisms
    ADD CONSTRAINT baptisms_pkey PRIMARY KEY (id);


--
-- Name: bible_studies bible_studies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bible_studies
    ADD CONSTRAINT bible_studies_pkey PRIMARY KEY (id);


--
-- Name: bible_study_participants bible_study_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bible_study_participants
    ADD CONSTRAINT bible_study_participants_pkey PRIMARY KEY (bible_study_id, candidate_id);


--
-- Name: candidates candidates_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_pkey PRIMARY KEY (id);


--
-- Name: certificate_download_logs certificate_download_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.certificate_download_logs
    ADD CONSTRAINT certificate_download_logs_pkey PRIMARY KEY (id);


--
-- Name: church_fields church_fields_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.church_fields
    ADD CONSTRAINT church_fields_pkey PRIMARY KEY (id);


--
-- Name: churches churches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.churches
    ADD CONSTRAINT churches_pkey PRIMARY KEY (id);


--
-- Name: cohort_members cohort_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cohort_members
    ADD CONSTRAINT cohort_members_pkey PRIMARY KEY (id);


--
-- Name: cohorts cohorts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cohorts
    ADD CONSTRAINT cohorts_pkey PRIMARY KEY (id);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: district_assignments district_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.district_assignments
    ADD CONSTRAINT district_assignments_pkey PRIMARY KEY (id);


--
-- Name: districts districts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.districts
    ADD CONSTRAINT districts_pkey PRIMARY KEY (id);


--
-- Name: email_verification_tokens email_verification_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (id);


--
-- Name: field_assignments field_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.field_assignments
    ADD CONSTRAINT field_assignments_pkey PRIMARY KEY (id);


--
-- Name: first_church_elders first_church_elders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.first_church_elders
    ADD CONSTRAINT first_church_elders_pkey PRIMARY KEY (id);


--
-- Name: human_support_messages human_support_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.human_support_messages
    ADD CONSTRAINT human_support_messages_pkey PRIMARY KEY (id);


--
-- Name: instructors instructors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.instructors
    ADD CONSTRAINT instructors_pkey PRIMARY KEY (id);


--
-- Name: leadership_audit_logs leadership_audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leadership_audit_logs
    ADD CONSTRAINT leadership_audit_logs_pkey PRIMARY KEY (id);


--
-- Name: lesson_answer lesson_answer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_answer
    ADD CONSTRAINT lesson_answer_pkey PRIMARY KEY (id);


--
-- Name: lesson_attempts lesson_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_attempts
    ADD CONSTRAINT lesson_attempts_pkey PRIMARY KEY (id);


--
-- Name: lesson_documents lesson_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_documents
    ADD CONSTRAINT lesson_documents_pkey PRIMARY KEY (id);


--
-- Name: lesson_question lesson_question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_question
    ADD CONSTRAINT lesson_question_pkey PRIMARY KEY (id);


--
-- Name: lessons lessons_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_pkey PRIMARY KEY (id);


--
-- Name: member_departments member_departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_departments
    ADD CONSTRAINT member_departments_pkey PRIMARY KEY (member_id, department_id);


--
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (id);


--
-- Name: membership_transfer membership_transfer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_transfer
    ADD CONSTRAINT membership_transfer_pkey PRIMARY KEY (id);


--
-- Name: message_logs message_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_logs
    ADD CONSTRAINT message_logs_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: report_audit_logs report_audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report_audit_logs
    ADD CONSTRAINT report_audit_logs_pkey PRIMARY KEY (id);


--
-- Name: spiritual_preparations spiritual_preparations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.spiritual_preparations
    ADD CONSTRAINT spiritual_preparations_pkey PRIMARY KEY (id);


--
-- Name: spiritual_progress spiritual_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.spiritual_progress
    ADD CONSTRAINT spiritual_progress_pkey PRIMARY KEY (id);


--
-- Name: cohort_members uk44jaqvpe4rh4frrgt8x8jng4k; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cohort_members
    ADD CONSTRAINT uk44jaqvpe4rh4frrgt8x8jng4k UNIQUE (cohort_id, candidate_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: members uk8l8vupcr5tjcdtg2wxvkfoam4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT uk8l8vupcr5tjcdtg2wxvkfoam4 UNIQUE (candidate_id);


--
-- Name: cohorts uk8s3dwys2se1yhbrafao1turhe; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cohorts
    ADD CONSTRAINT uk8s3dwys2se1yhbrafao1turhe UNIQUE (cohort_code);


--
-- Name: users ukdu5v5sr43g5bfnji4vb8hg5s3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukdu5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone);


--
-- Name: email_verification_tokens ukewmvysc7e9y6uy7og2c21axa9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT ukewmvysc7e9y6uy7og2c21axa9 UNIQUE (token);


--
-- Name: unions unions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unions
    ADD CONSTRAINT unions_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users fk11ian055i0p45mnesyljkrx1l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk11ian055i0p45mnesyljkrx1l FOREIGN KEY (field_id) REFERENCES public.church_fields(id);


--
-- Name: departments fk11my46q9d916vb2ppw6er3ka9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT fk11my46q9d916vb2ppw6er3ka9 FOREIGN KEY (head_member_id) REFERENCES public.members(id);


--
-- Name: member_departments fk1qbkj5jhe83mo5ieeik2u1tsa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_departments
    ADD CONSTRAINT fk1qbkj5jhe83mo5ieeik2u1tsa FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: field_assignments fk1vwhef3wbffe9hn1lnvtitcyi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.field_assignments
    ADD CONSTRAINT fk1vwhef3wbffe9hn1lnvtitcyi FOREIGN KEY (field_id) REFERENCES public.church_fields(id);


--
-- Name: human_support_messages fk2o6cj50owiro70qt7hh999eup; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.human_support_messages
    ADD CONSTRAINT fk2o6cj50owiro70qt7hh999eup FOREIGN KEY (recipient_id) REFERENCES public.users(id);


--
-- Name: spiritual_preparations fk2t1y97lwqlxqdutndw4s6eidd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.spiritual_preparations
    ADD CONSTRAINT fk2t1y97lwqlxqdutndw4s6eidd FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: users fk33gytyitta3x6tkmiv6u5qths; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk33gytyitta3x6tkmiv6u5qths FOREIGN KEY (church_id) REFERENCES public.churches(id);


--
-- Name: baptism_photo_urls fk3b3iu4sdy9stkfa6f48wcyjsh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baptism_photo_urls
    ADD CONSTRAINT fk3b3iu4sdy9stkfa6f48wcyjsh FOREIGN KEY (baptism_id) REFERENCES public.baptisms(id);


--
-- Name: churches fk3lsuiq0607xc7ivf73b71fr86; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.churches
    ADD CONSTRAINT fk3lsuiq0607xc7ivf73b71fr86 FOREIGN KEY (pastor_id) REFERENCES public.users(id);


--
-- Name: baptisms fk3me3310vni00s40hl7auy2sq3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baptisms
    ADD CONSTRAINT fk3me3310vni00s40hl7auy2sq3 FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: departments fk3n1nti5twp7icu17u2e4s677a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT fk3n1nti5twp7icu17u2e4s677a FOREIGN KEY (church_id) REFERENCES public.churches(id);


--
-- Name: cohorts fk4qbpnmeflyaxapb5m9rn21fb1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cohorts
    ADD CONSTRAINT fk4qbpnmeflyaxapb5m9rn21fb1 FOREIGN KEY (church_id) REFERENCES public.churches(id);


--
-- Name: messages fk4ui4nnwntodh6wjvck53dbk9m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk4ui4nnwntodh6wjvck53dbk9m FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: lessons fk67t9pyepga3257rm2tb0br76t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fk67t9pyepga3257rm2tb0br76t FOREIGN KEY (instructor_id) REFERENCES public.instructors(id);


--
-- Name: baptisms fk75bwsirm7jqvsc65up00bchab; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baptisms
    ADD CONSTRAINT fk75bwsirm7jqvsc65up00bchab FOREIGN KEY (event_id) REFERENCES public.baptism_events(id);


--
-- Name: human_support_messages fk75yojlt5xiullt4f5gl0ey6sx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.human_support_messages
    ADD CONSTRAINT fk75yojlt5xiullt4f5gl0ey6sx FOREIGN KEY (parent_id) REFERENCES public.human_support_messages(id);


--
-- Name: bible_studies fk84wfvjqndyfi5bo6lud9cc38w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bible_studies
    ADD CONSTRAINT fk84wfvjqndyfi5bo6lud9cc38w FOREIGN KEY (instructor_id) REFERENCES public.instructors(id);


--
-- Name: bible_study_participants fk8fals491aqiagnvu00duo0ufi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bible_study_participants
    ADD CONSTRAINT fk8fals491aqiagnvu00duo0ufi FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: districts fk8fl8ipkwb08nejtdb5u50ppu8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.districts
    ADD CONSTRAINT fk8fl8ipkwb08nejtdb5u50ppu8 FOREIGN KEY (field_id) REFERENCES public.church_fields(id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: membership_transfer fka96b49jiu2p10oiha93u51iuc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_transfer
    ADD CONSTRAINT fka96b49jiu2p10oiha93u51iuc FOREIGN KEY (approved_by_to_church_id) REFERENCES public.users(id);


--
-- Name: human_support_messages fkad2iro0vlxkw5u3vhf61tusmg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.human_support_messages
    ADD CONSTRAINT fkad2iro0vlxkw5u3vhf61tusmg FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: churches fkal3h9ke6vlo27yjl0elu005yl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.churches
    ADD CONSTRAINT fkal3h9ke6vlo27yjl0elu005yl FOREIGN KEY (district_id) REFERENCES public.districts(id);


--
-- Name: cohorts fkb404gthk2kb199xj478742t6p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cohorts
    ADD CONSTRAINT fkb404gthk2kb199xj478742t6p FOREIGN KEY (instructor_id) REFERENCES public.instructors(id);


--
-- Name: church_fields fkbq1y2po2jcq4yywb15hxu3329; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.church_fields
    ADD CONSTRAINT fkbq1y2po2jcq4yywb15hxu3329 FOREIGN KEY (union_id) REFERENCES public.unions(id);


--
-- Name: district_assignments fkc0wtc5xir9krp9k25we9m6uip; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.district_assignments
    ADD CONSTRAINT fkc0wtc5xir9krp9k25we9m6uip FOREIGN KEY (district_id) REFERENCES public.districts(id);


--
-- Name: attendance fkcoid2wjhnhntj4575w6iuc2cs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fkcoid2wjhnhntj4575w6iuc2cs FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: membership_transfer fkd2nl7g6weu02kli3adrscqcw3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_transfer
    ADD CONSTRAINT fkd2nl7g6weu02kli3adrscqcw3 FOREIGN KEY (to_church_id) REFERENCES public.churches(id);


--
-- Name: membership_transfer fkdaeysrqsglpa63gpb39caktsp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_transfer
    ADD CONSTRAINT fkdaeysrqsglpa63gpb39caktsp FOREIGN KEY (from_church_id) REFERENCES public.churches(id);


--
-- Name: ai_chat_messages fkdf1ntoi8a3yh23oravj5tjpfc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_chat_messages
    ADD CONSTRAINT fkdf1ntoi8a3yh23oravj5tjpfc FOREIGN KEY (chat_id) REFERENCES public.ai_chats(id);


--
-- Name: spiritual_progress fkdt218500dkiidrwan61khy44e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.spiritual_progress
    ADD CONSTRAINT fkdt218500dkiidrwan61khy44e FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: human_support_messages fkdxjrpeoqs7fvbivxbgadkxqng; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.human_support_messages
    ADD CONSTRAINT fkdxjrpeoqs7fvbivxbgadkxqng FOREIGN KEY (candidate_id) REFERENCES public.users(id);


--
-- Name: baptism_interview fke09v7u6fdg7eer66epylupuu0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baptism_interview
    ADD CONSTRAINT fke09v7u6fdg7eer66epylupuu0 FOREIGN KEY (interviewer_id) REFERENCES public.instructors(id);


--
-- Name: baptism_interview fkeew6odry12gkgg41t3lquo288; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baptism_interview
    ADD CONSTRAINT fkeew6odry12gkgg41t3lquo288 FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: lesson_answer fkev4u5acsym2as96fnogs69wjk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_answer
    ADD CONSTRAINT fkev4u5acsym2as96fnogs69wjk FOREIGN KEY (question_id) REFERENCES public.lesson_question(id);


--
-- Name: field_assignments fkfufrp20kaxn60di1xu09iuqi8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.field_assignments
    ADD CONSTRAINT fkfufrp20kaxn60di1xu09iuqi8 FOREIGN KEY (head_id) REFERENCES public.users(id);


--
-- Name: lesson_attempts fkgx7cuhguorik7nwaxnhqm6amt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_attempts
    ADD CONSTRAINT fkgx7cuhguorik7nwaxnhqm6amt FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);


--
-- Name: cohort_members fkgy8nwcaxd43mdk55eh7o30e4h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cohort_members
    ADD CONSTRAINT fkgy8nwcaxd43mdk55eh7o30e4h FOREIGN KEY (cohort_id) REFERENCES public.cohorts(id);


--
-- Name: members fkhedn55pydevxnew4xd83nphut; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT fkhedn55pydevxnew4xd83nphut FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: email_verification_tokens fki1c4mmamlb8keqt74k4lrtwhc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT fki1c4mmamlb8keqt74k4lrtwhc FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: lesson_question fki9mresan8ujipiqdnn001x80v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_question
    ADD CONSTRAINT fki9mresan8ujipiqdnn001x80v FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);


--
-- Name: first_church_elders fkipjmfha3v51e89qspmpoygbqr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.first_church_elders
    ADD CONSTRAINT fkipjmfha3v51e89qspmpoygbqr FOREIGN KEY (church_id) REFERENCES public.churches(id);


--
-- Name: users fkj30hhy45scxdgcj0usq90504r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkj30hhy45scxdgcj0usq90504r FOREIGN KEY (district_id) REFERENCES public.districts(id);


--
-- Name: ai_chats fkjdbdhlu993lipf1wkb3p9mcjn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_chats
    ADD CONSTRAINT fkjdbdhlu993lipf1wkb3p9mcjn FOREIGN KEY (candidate_id) REFERENCES public.users(id);


--
-- Name: membership_transfer fkjdxeu4178ljwo97kia4jj2y4n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_transfer
    ADD CONSTRAINT fkjdxeu4178ljwo97kia4jj2y4n FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: membership_transfer fkjg253kxpx9nefjrhkamyrbagw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_transfer
    ADD CONSTRAINT fkjg253kxpx9nefjrhkamyrbagw FOREIGN KEY (requested_by_id) REFERENCES public.users(id);


--
-- Name: password_reset_tokens fkk3ndxg5xp6v7wd4gjyusp15gq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: member_departments fkk9yta8omfuqfba01hwibg5u8f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_departments
    ADD CONSTRAINT fkk9yta8omfuqfba01hwibg5u8f FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: users fkl9if8gaau95iju5xmkjwo65qs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkl9if8gaau95iju5xmkjwo65qs FOREIGN KEY (union_id) REFERENCES public.unions(id);


--
-- Name: lesson_answer fklpwwxueletp5i06jdlmvj8ks0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_answer
    ADD CONSTRAINT fklpwwxueletp5i06jdlmvj8ks0 FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: lesson_attempts fklvsilwk3kveicpuaptdyapuk7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_attempts
    ADD CONSTRAINT fklvsilwk3kveicpuaptdyapuk7 FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: lessons fkm1gdd96jj7i10oxegaxy0pi64; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fkm1gdd96jj7i10oxegaxy0pi64 FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: district_assignments fkmswuedbt3ssfcv3h1npkgfknj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.district_assignments
    ADD CONSTRAINT fkmswuedbt3ssfcv3h1npkgfknj FOREIGN KEY (pastor_id) REFERENCES public.users(id);


--
-- Name: bible_study_participants fkns6t3j623tbptq9ioc4gq9ypf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bible_study_participants
    ADD CONSTRAINT fkns6t3j623tbptq9ioc4gq9ypf FOREIGN KEY (bible_study_id) REFERENCES public.bible_studies(id);


--
-- Name: lesson_question_options fko1a0nlagoow8koyc1vdh845p3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_question_options
    ADD CONSTRAINT fko1a0nlagoow8koyc1vdh845p3 FOREIGN KEY (lesson_question_id) REFERENCES public.lesson_question(id);


--
-- Name: lessons fkoqd5jtp1daqex5tb1rg08b0r1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fkoqd5jtp1daqex5tb1rg08b0r1 FOREIGN KEY (bible_study_id) REFERENCES public.bible_studies(id);


--
-- Name: membership_transfer fkoxlgojgibtqf0ofyaeutoemcw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_transfer
    ADD CONSTRAINT fkoxlgojgibtqf0ofyaeutoemcw FOREIGN KEY (approved_by_from_church_id) REFERENCES public.users(id);


--
-- Name: candidates fkrcq316d2oml13yxp38b96tdi2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT fkrcq316d2oml13yxp38b96tdi2 FOREIGN KEY (church_id) REFERENCES public.churches(id);


--
-- Name: instructors fkrtrnvc0vuf50pevi7pvljnh97; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.instructors
    ADD CONSTRAINT fkrtrnvc0vuf50pevi7pvljnh97 FOREIGN KEY (church_id) REFERENCES public.churches(id);


--
-- Name: candidates fks56daxhosmww4ojs9m6erbjwr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT fks56daxhosmww4ojs9m6erbjwr FOREIGN KEY (instructor_id) REFERENCES public.instructors(id);


--
-- Name: messages fkt05r0b6n0iis8u7dfna4xdh73; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkt05r0b6n0iis8u7dfna4xdh73 FOREIGN KEY (receiver_id) REFERENCES public.users(id);


--
-- Name: cohort_members fktfl7w75pmfm3i1gd7heab7gnj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cohort_members
    ADD CONSTRAINT fktfl7w75pmfm3i1gd7heab7gnj FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- PostgreSQL database dump complete
--

\unrestrict vlSJY3MTeQKRdU48fnEDdysSYjg3WlQDzB44I7RQC2daydHvZYbzd4q9TUivLVQ

