server.port=8081
spring.application.name=baptism-membership-system
spring.datasource.url=jdbc:postgresql://localhost:5432/BMPMS
spring.datasource.username=postgres
spring.datasource.password=benny123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mail (SMTP) Configuration for 2FA
# Replace with your SMTP settings (e.g., Gmail app password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nsengiyumvabenny1@gmail.com
spring.mail.password=akcw yuvj qqjs cues
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Custom app configuration
app.frontend-url=http://localhost:5173