package com.church.baptism.service.report;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

@Service
public class ReportPdfService {

    private static final BaseColor NAVY = new BaseColor(11, 52, 117);
    private static final BaseColor WHITE = BaseColor.WHITE;
    private static final BaseColor BLACK = BaseColor.BLACK;
    private static final BaseColor DARK = new BaseColor(40, 40, 40);
    private static final BaseColor GRAY = new BaseColor(100, 100, 100);
    private static final BaseColor LIGHT_GRAY = new BaseColor(246, 248, 250);
    private static final BaseColor BORDER = new BaseColor(210, 215, 220);
    private static final BaseColor GREEN = new BaseColor(16, 120, 50);
    private static final BaseColor RED = new BaseColor(200, 30, 30);

    private static Font f(String name, float size, BaseColor color) {
        return FontFactory.getFont(name, size, Font.NORMAL, color);
    }
    private static Font fb(String name, float size, BaseColor color) {
        return FontFactory.getFont(name, size, Font.BOLD, color);
    }

    public byte[] generateReport(
            String title,
            List<String> infoLines,
            String dateRange,
            List<String> headers,
            List<List<String>> rows,
            Map<String, Long> summary
    ) {
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            Document doc = new Document(PageSize.A4, 36, 36, 30, 50);
            PdfWriter writer = PdfWriter.getInstance(doc, out);
            writer.setPageEvent(new FooterEvent());
            doc.open();

            LocalDateTime now = LocalDateTime.now();
            String generatedBy = infoLines.size() > 1 ? infoLines.get(1).replace("Generated by: ", "") : "System";

            addHeader(doc, title, dateRange, now);
            addDivider(doc);
            addReportTitle(doc, title);
            addTable(doc, headers, rows);
            addTotalRow(doc, rows.size());
            addPreparedApprovedSection(doc, generatedBy);

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Error generating PDF report", e);
        }
    }

    private void addHeader(Document doc, String title, String dateRange, LocalDateTime now) throws DocumentException, IOException {
        PdfPTable t = new PdfPTable(new float[]{22f, 50f, 28f});
        t.setWidthPercentage(100);

        // LEFT: Logo + Church name
        PdfPCell logo = new PdfPCell();
        logo.setBorder(Rectangle.NO_BORDER);
        logo.setVerticalAlignment(Element.ALIGN_TOP);
        try {
            ClassPathResource r = new ClassPathResource("static/images/sda-logo.png");
            if (r.exists()) {
                Image img = Image.getInstance(r.getInputStream().readAllBytes());
                img.scaleToFit(55, 55);
                logo.addElement(img);
            }
        } catch (IOException ignored) {}
        Paragraph church = new Paragraph("Seventh-day Adventist Church", f(FontFactory.HELVETICA, 9, GRAY));
        church.setSpacingBefore(3);
        logo.addElement(church);
        t.addCell(logo);

        // CENTER: Title
        PdfPCell tc = new PdfPCell();
        tc.setBorder(Rectangle.NO_BORDER);
        tc.setVerticalAlignment(Element.ALIGN_MIDDLE);
        tc.setHorizontalAlignment(Element.ALIGN_CENTER);
        Paragraph p1 = new Paragraph("BAPTISM & MEMBERSHIP", fb(FontFactory.HELVETICA_BOLD, 17, NAVY));
        p1.setAlignment(Element.ALIGN_CENTER);
        tc.addElement(p1);
        Paragraph p2 = new Paragraph("PREPARATION MANAGEMENT SYSTEM", fb(FontFactory.HELVETICA_BOLD, 10, NAVY));
        p2.setAlignment(Element.ALIGN_CENTER);
        p2.setSpacingBefore(2);
        tc.addElement(p2);
        t.addCell(tc);

        // RIGHT: Date/Time + Date Range
        PdfPCell rc = new PdfPCell();
        rc.setBorder(Rectangle.NO_BORDER);
        rc.setVerticalAlignment(Element.ALIGN_TOP);
        rc.setHorizontalAlignment(Element.ALIGN_RIGHT);

        Paragraph gl = new Paragraph("Report generated on", f(FontFactory.HELVETICA, 8, GRAY));
        gl.setAlignment(Element.ALIGN_RIGHT);
        rc.addElement(gl);

        DateTimeFormatter df = DateTimeFormatter.ofPattern("dd MMMM yyyy");
        Paragraph dv = new Paragraph(now.format(df), fb(FontFactory.HELVETICA_BOLD, 10, BLACK));
        dv.setAlignment(Element.ALIGN_RIGHT);
        dv.setSpacingBefore(2);
        rc.addElement(dv);

        DateTimeFormatter tf = DateTimeFormatter.ofPattern("HH:mm");
        Paragraph tv = new Paragraph(now.format(tf), f(FontFactory.HELVETICA, 9, GRAY));
        tv.setAlignment(Element.ALIGN_RIGHT);
        tv.setSpacingBefore(1);
        rc.addElement(tv);

        if (dateRange != null && !dateRange.isEmpty()) {
            Paragraph dr = new Paragraph("Date Range:", fb(FontFactory.HELVETICA_BOLD, 8, GRAY));
            dr.setAlignment(Element.ALIGN_RIGHT);
            dr.setSpacingBefore(8);
            rc.addElement(dr);
            Paragraph drv = new Paragraph(dateRange, f(FontFactory.HELVETICA, 8, GRAY));
            drv.setAlignment(Element.ALIGN_RIGHT);
            drv.setSpacingBefore(1);
            rc.addElement(drv);
        }

        t.addCell(rc);
        doc.add(t);
    }

    private void addDivider(Document doc) throws DocumentException {
        PdfPTable t = new PdfPTable(1);
        t.setWidthPercentage(100);
        t.setSpacingBefore(8);
        t.setSpacingAfter(6);
        PdfPCell c = new PdfPCell();
        c.setBackgroundColor(NAVY);
        c.setFixedHeight(1.5f);
        c.setBorder(Rectangle.NO_BORDER);
        t.addCell(c);
        doc.add(t);
    }

    private void addReportTitle(Document doc, String title) throws DocumentException {
        Paragraph p = new Paragraph(title, fb(FontFactory.HELVETICA_BOLD, 13, NAVY));
        p.setAlignment(Element.ALIGN_LEFT);
        p.setSpacingAfter(8);
        doc.add(p);
    }

    private void addTable(Document doc, List<String> headers, List<List<String>> rows) throws DocumentException {
        PdfPTable table = new PdfPTable(headers.size());
        table.setWidthPercentage(100);
        table.setLockedWidth(true);
        table.setTotalWidth(doc.getPageSize().getWidth() - 72);

        float[] widths = calcWidths(headers, rows, doc.getPageSize().getWidth() - 72);
        try { table.setWidths(widths); } catch (Exception ignored) {}

        // Adaptive font size based on column count
        float headerFontSize = headers.size() > 6 ? 7.5f : 8.5f;
        float cellFontSize = headers.size() > 6 ? 7f : 8f;
        float cellPadding = headers.size() > 7 ? 4f : 5f;
        float headerPadding = headers.size() > 7 ? 4f : 5f;

        // Header
        for (String h : headers) {
            PdfPCell c = new PdfPCell(new Phrase(h, fb(FontFactory.HELVETICA_BOLD, headerFontSize, WHITE)));
            c.setBackgroundColor(NAVY);
            c.setPadding(headerPadding);
            c.setHorizontalAlignment(Element.ALIGN_CENTER);
            c.setVerticalAlignment(Element.ALIGN_MIDDLE);
            c.setBorder(Rectangle.RECTANGLE);
            c.setBorderColor(NAVY);
            c.setBorderWidth(0.5f);
            table.addCell(c);
        }

        // Rows
        for (int r = 0; r < rows.size(); r++) {
            List<String> row = rows.get(r);
            BaseColor bg = r % 2 == 0 ? WHITE : LIGHT_GRAY;
            for (int c = 0; c < row.size(); c++) {
                String val = row.get(c) != null ? row.get(c) : "";
                PdfPCell cell;
                if (val.equalsIgnoreCase("Yes") || val.equalsIgnoreCase("No")) {
                    cell = new PdfPCell(new Phrase(val, fb(FontFactory.HELVETICA_BOLD, cellFontSize, val.equalsIgnoreCase("Yes") ? GREEN : RED)));
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                } else if (isStatus(val)) {
                    cell = statusCell(val);
                } else {
                    cell = new PdfPCell(new Phrase(val, f(FontFactory.HELVETICA, cellFontSize, DARK)));
                }
                cell.setBackgroundColor(bg);
                cell.setPadding(cellPadding);
                cell.setLeading(10, 1.1f);
                cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
                cell.setBorder(Rectangle.RECTANGLE);
                cell.setBorderColor(BORDER);
                cell.setBorderWidth(0.3f);
                if (c == 0) cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                // Prevent wrapping for short values, emails, phones, dates, numbers
                String headerLower = headers.get(c).toLowerCase();
                boolean isCompact = headerLower.contains("email") || headerLower.contains("phone")
                        || headerLower.contains("date") || headerLower.contains("success")
                        || headerLower.contains("role") || headerLower.contains("action")
                        || headerLower.contains("#") || headerLower.contains("format")
                        || headerLower.contains("count") || headerLower.contains("record")
                        || headerLower.contains("status") || val.length() <= 25;
                if (isCompact) {
                    cell.setNoWrap(true);
                }
                table.addCell(cell);
            }
        }
        doc.add(table);
    }

    private PdfPCell statusCell(String status) {
        String l = status.toLowerCase().trim().replace("_", " ");
        BaseColor fg, bg;
        if (l.contains("active") || l.contains("approved") || l.contains("completed") || l.contains("baptized") || l.contains("enrolled")) {
            fg = GREEN; bg = new BaseColor(230, 250, 235);
        } else if (l.contains("pending") || l.contains("draft") || l.contains("request")) {
            fg = new BaseColor(160, 100, 10); bg = new BaseColor(255, 248, 220);
        } else if (l.contains("inactive") || l.contains("rejected") || l.contains("cancelled") || l.contains("withdrawn")) {
            fg = RED; bg = new BaseColor(255, 235, 235);
        } else {
            fg = new BaseColor(70, 85, 105); bg = new BaseColor(240, 243, 247);
        }
        String d = status.replace("_", " ");
        if (d.length() > 22) d = d.substring(0, 20) + "..";
        PdfPCell c = new PdfPCell(new Phrase(d, fb(FontFactory.HELVETICA_BOLD, 8, fg)));
        c.setBackgroundColor(bg);
        c.setHorizontalAlignment(Element.ALIGN_CENTER);
        c.setPadding(4);
        c.setBorder(Rectangle.NO_BORDER);
        return c;
    }

    private boolean isStatus(String v) {
        if (v == null) return false;
        String l = v.toLowerCase().trim();
        return l.equals("active") || l.equals("inactive") || l.equals("pending") || l.equals("completed")
                || l.equals("approved") || l.equals("rejected") || l.equals("baptized") || l.equals("registered")
                || l.equals("enrolled") || l.equals("draft") || l.equals("cancelled") || l.equals("archived")
                || l.equals("withdrawn") || l.contains("request") || l.contains("progress");
    }

    private void addTotalRow(Document doc, int count) throws DocumentException {
        PdfPTable t = new PdfPTable(1);
        t.setWidthPercentage(100);
        t.setSpacingBefore(6);
        PdfPCell c = new PdfPCell(new Phrase("Total Records:  " + count, fb(FontFactory.HELVETICA_BOLD, 10, NAVY)));
        c.setBorder(Rectangle.NO_BORDER);
        c.setPadding(4);
        t.addCell(c);
        doc.add(t);
    }

    private void addPreparedApprovedSection(Document doc, String generatedBy) throws DocumentException {
        doc.add(new Paragraph(" "));

        PdfPTable divider = new PdfPTable(1);
        divider.setWidthPercentage(100);
        PdfPCell dc = new PdfPCell();
        dc.setBackgroundColor(NAVY);
        dc.setFixedHeight(1.5f);
        dc.setBorder(Rectangle.NO_BORDER);
        divider.addCell(dc);
        doc.add(divider);

        doc.add(new Paragraph(" "));

        PdfPTable t = new PdfPTable(new float[]{50f, 50f});
        t.setWidthPercentage(100);

        // LEFT: PREPARED BY
        PdfPCell left = new PdfPCell();
        left.setBorder(Rectangle.NO_BORDER);
        left.setVerticalAlignment(Element.ALIGN_TOP);

        Paragraph prepTitle = new Paragraph("PREPARED BY:", fb(FontFactory.HELVETICA_BOLD, 9, NAVY));
        prepTitle.setSpacingAfter(4);
        left.addElement(prepTitle);

        Paragraph userName = new Paragraph(generatedBy, fb(FontFactory.HELVETICA_BOLD, 10, DARK));
        left.addElement(userName);

        Paragraph sys1 = new Paragraph("Baptism & Membership Preparation", f(FontFactory.HELVETICA, 8, GRAY));
        sys1.setSpacingBefore(4);
        left.addElement(sys1);

        Paragraph sys2 = new Paragraph("Management System (BMPMS)", f(FontFactory.HELVETICA, 8, GRAY));
        left.addElement(sys2);

        Paragraph sys3 = new Paragraph("Seventh-day Adventist Church", f(FontFactory.HELVETICA, 8, GRAY));
        left.addElement(sys3);

        Paragraph contact = new Paragraph("Contact: admin@bmpms.org", f(FontFactory.HELVETICA, 8, GRAY));
        contact.setSpacingBefore(4);
        left.addElement(contact);

        t.addCell(left);

        // RIGHT: APPROVED BY
        PdfPCell right = new PdfPCell();
        right.setBorder(Rectangle.NO_BORDER);
        right.setVerticalAlignment(Element.ALIGN_TOP);
        right.setHorizontalAlignment(Element.ALIGN_RIGHT);

        Paragraph apprTitle = new Paragraph("APPROVED BY:", fb(FontFactory.HELVETICA_BOLD, 9, NAVY));
        apprTitle.setSpacingAfter(4);
        right.addElement(apprTitle);

        Paragraph sigLine = new Paragraph("_________________________", f(FontFactory.HELVETICA, 9, GRAY));
        sigLine.setSpacingBefore(24);
        right.addElement(sigLine);

        Paragraph sigLabel = new Paragraph("Signature & Date", f(FontFactory.HELVETICA, 8, GRAY));
        sigLabel.setSpacingBefore(2);
        right.addElement(sigLabel);

        t.addCell(right);

        doc.add(t);
    }

    private float[] calcWidths(List<String> headers, List<List<String>> rows, float total) {
        int n = headers.size();
        float[] s = new float[n];
        // Start with header length as base
        for (int i = 0; i < n; i++) s[i] = Math.max(headers.get(i).length() * 1.1f, 6);
        // Scale by max content length per column
        for (List<String> row : rows) {
            for (int i = 0; i < n && i < row.size(); i++) {
                String val = row.get(i);
                if (val != null) {
                    // Account for word wrapping: count words and estimate width
                    int len = val.length();
                    if (len > 30) len = (int)(30 + (len - 30) * 0.5f); // long text wraps, less width needed
                    s[i] = Math.max(s[i], len);
                }
            }
        }
        // Apply minimum widths based on column type
        for (int i = 0; i < n; i++) {
            String h = headers.get(i).toLowerCase();
            if (h.equals("#") || h.equals("sn")) s[i] = Math.max(s[i], 4);
            else if (h.contains("email")) s[i] = Math.max(s[i], 32);
            else if (h.contains("date") || h.contains("created") || h.contains("registered")) s[i] = Math.max(s[i], 16);
            else if (h.contains("status") || h.contains("success") || h.contains("approved") || h.contains("signed")) s[i] = Math.max(s[i], 12);
            else if (h.contains("name") || h.contains("candidate") || h.contains("instructor") || h.contains("pastor")) s[i] = Math.max(s[i], 18);
            else if (h.contains("church") || h.contains("district") || h.contains("field") || h.contains("location")) s[i] = Math.max(s[i], 18);
            else if (h.contains("action") || h.contains("role") || h.contains("phone")) s[i] = Math.max(s[i], 12);
            else if (h.contains("registration") || h.contains("count") || h.contains("completion")) s[i] = Math.max(s[i], 12);
            else if (h.contains("event") || h.contains("description") || h.contains("subject")) s[i] = Math.max(s[i], 20);
            else if (h.contains("certificate") || h.contains("download")) s[i] = Math.max(s[i], 16);
            else s[i] = Math.max(s[i], 12);
        }
        // Normalize to total width
        float sum = 0;
        for (float v : s) sum += v;
        float[] w = new float[n];
        for (int i = 0; i < n; i++) {
            w[i] = (s[i] / sum) * total;
            w[i] = Math.max(w[i], 40f); // minimum column width
            w[i] = Math.min(w[i], (float)(total * 0.40)); // max 40% of page
        }
        // Re-normalize after clamping
        float nt = 0;
        for (float v : w) nt += v;
        for (int i = 0; i < n; i++) w[i] = (w[i] / nt) * total;
        return w;
    }

    private static class FooterEvent extends PdfPageEventHelper {
        @Override
        public void onEndPage(PdfWriter writer, Document doc) {
            try {
                PdfPTable footer = new PdfPTable(3);
                footer.setWidthPercentage(100);
                footer.setTotalWidth(doc.getPageSize().getWidth() - 72);

                Font sf = FontFactory.getFont(FontFactory.HELVETICA, 8, new BaseColor(100, 100, 100));
                Font sb = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8, new BaseColor(100, 100, 100));

                PdfPCell left = new PdfPCell(new Phrase("BMPMS Report", sf));
                left.setBorder(Rectangle.NO_BORDER);
                left.setHorizontalAlignment(Element.ALIGN_LEFT);
                footer.addCell(left);

                PdfPCell center = new PdfPCell(new Phrase("Page " + writer.getPageNumber(), sb));
                center.setBorder(Rectangle.NO_BORDER);
                center.setHorizontalAlignment(Element.ALIGN_CENTER);
                footer.addCell(center);

                PdfPCell right = new PdfPCell(new Phrase("Confidential", sf));
                right.setBorder(Rectangle.NO_BORDER);
                right.setHorizontalAlignment(Element.ALIGN_RIGHT);
                footer.addCell(right);

                footer.writeSelectedRows(0, -1, 36, 25, writer.getDirectContent());

                // Thin blue line above footer
                PdfContentByte cb = writer.getDirectContent();
                cb.setColorStroke(new BaseColor(11, 52, 117));
                cb.setLineWidth(0.5f);
                cb.moveTo(36, 30);
                cb.lineTo(doc.getPageSize().getWidth() - 36, 30);
                cb.stroke();
            } catch (Exception ignored) {}
        }
    }
}
